package com.app.controller.user;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.dto.OtherDto;
import com.app.dto.ResultDto;
import com.app.pojos.CheckOutBook;
import com.app.service.ReturnBookServiceImpl;

@RestController
@RequestMapping("/user/returnBook")
@CrossOrigin("http://localhost:3060")
public class UserReturnBookController {

	@Autowired
	ReturnBookServiceImpl returnBookServiceImpl;
	
	public UserReturnBookController() {
		System.out.println("in ctor of "+getClass().getName());
	}
	
	
	@PutMapping("/return-book-by-user")
	public ResponseEntity<?> returnBookByUser(@RequestBody OtherDto otherDto){
		System.out.println("in method of returnBookByUser of "+getClass().getName()+" "+otherDto.getId());
		ResultDto result=new ResultDto("error","something went wrong");
		try {
			int id=(Integer)otherDto.getId();
			
		} catch (Exception e) {
			System.out.println("exception caught in returnBookByUser of "+getClass().getName());
			System.out.println(e.getMessage());
			result.setData(e.getMessage());
		}
		return ResponseEntity.ok(result);
	}
	
	
	

}
