package com.app.controller.librarian;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

import com.app.dto.OtherDto;
import com.app.dto.ResultDto;
import com.app.pojos.CheckOutBook;
import com.app.service.CheckOutBookServiceImpl;
import com.app.service.ReserveBookHistoryServiceImpl;

public class LibrarianCheckOutBookController {

	@Autowired
	CheckOutBookServiceImpl checkOutBookServiceImpl;
	
	@Autowired
	ReserveBookHistoryServiceImpl reserveBookHistoryServiceImpl;
	
	public LibrarianCheckOutBookController() {
		System.out.println("in ctor of "+getClass().getName());
	}
	
	
	@PutMapping("/check-out-by-user")
	public ResponseEntity<?> checkOutBookByLibrary(@RequestBody OtherDto otherDto){
		System.out.println("in method of checkOutBookByUser of "+getClass().getName()+" "+otherDto.getId());
		ResultDto result=new ResultDto("error","something went wrong");
		try {
			int id=(Integer)otherDto.getId();
			CheckOutBook c=checkOutBookServiceImpl.getCheckOutBookById(id);
			if(c!=null) {
				c.setUserCheckedOut(1);
				CheckOutBook c1=checkOutBookServiceImpl.addCheckOutBook(c);
				if(c1!=null) {
					result.setData("book checked out successfully");
					result.setStatus("success");
				}else {
					result.setData("something went wrong while checking out");
				}
			}else {
				result.setData("check out book id is invalid");
			}
		} catch (Exception e) {
			System.out.println("exception caught in checkOutBookByUser of "+getClass().getName());
			System.out.println(e.getMessage());
			result.setData(e.getMessage());
		}
		return ResponseEntity.ok(result);
	}
	

}
